# Generated by Django 4.2.11 on 2024-09-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(null=True, upload_to='Arcaimg'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='title_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
